package Study.App.model.enums;

public enum Department {
    AGRICULTURAL_AND_ENVIRONMENTAL_SCIENCES,
    ARTS,
    SCHOOL_OF_CONTINUING_STUDIES,
    DENTAL_MEDICINE_AND_ORAL_HEALTH_SCIENCES,
    EDUCATION,
    ENGINEERING,
    GRADUATE_AND_POSTDOCTORAL_STUDIES,
    LAW,
    DESAUTELS_MANAGEMENT,
    MEDICINE_AND_HEALTH_SCIENCES,
    SCHULICH_SCHOOL_OF_MUSIC,
    SCIENCE,
}
