package Study.App.model.enums;

public enum Program {
    // list must be curated from mcgill website
    LABOUR_MANAGEMENT_RELATIONS_AND_HUMAN_RESOURCES,
    ACCOUNTING,
    MARKETING,
    STATISTICS,
    INTERNATIONAL_AGRICULTURE,
    INFORMATION_SYSTEMS,
    ECONOMICS_AND_ACCOUNTING,
    MANAGEMENT_RELATIONS_AND_HUMAN_RESOURCES,
    INTERNATIONAL_DEVELOPMENT_STUDIES,
    
    
}
